# Site settings
name: twilexis
description: "Find me at..."
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  twilexis
facebook_username: twilexis
twitter_username: KOStwilexis
steam_username: twilexis
soundcloud_username:  twilexis
reddit_username: twilexis
email: twilexis@twilexis.com



avatar: yes
avatar_img_path: "imgs/twilexis.png"

#You can link to your GitHub image. That way it will get updated 
#automatically whenever you change your GitHub profile picture
#avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

# Build settings
markdown: kramdown
permalink: pretty
